### ISSUE TITLE
Fail to Retrieve Activity when Accessing Organization

### ISSUE THREAD

**Issue by ghost** [taqui-786/GitEstimate#2]
When you enter the name of an organization instead of a user, it can't grab the graph (because GitHub doesn't track activity in organizations like that):

![image](https://github.com/taqui-786/GitEstimate/assets/144612896/4b848535-0ad2-4ee7-b8a3-b6eec531b128)

Perhaps you could show a graph with stars instead? Also, there's a typo for the alt text (Contribution instead of Contrbuition). Great project!

**Comment by taqui-786** [comment]
Thank you so much aarvinr for i am not really aware of this bug . Actually i build this project in 2hrs because i am very hurry and i forgot to test it properly. Bug is fixed .
